#pragma once
#define ROCKSETTINGS_H
#define ROCK_SMALL_RADIUS 12
#define ROCK_MED_RADIUS 25
#define ROCK_BIG_RADIUS 50
#define ROCK_DEVIATION_MIN 0.75
#define ROCK_DEVIATION_MAX 1.25
#define ROCK_PARTS 10
